version: 2.1
orbs:
  node: circleci/node@4.4.0
  codecov: codecov/codecov@1.0.2

jobs:
  lint:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run lint
  build-and-test:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run test
      - run: npm run codecov
      - store_artifacts:
          path: coverage.lcov
          destination: coverage.lcov

      - codecov/upload:
          file: coverage.lcov
workflows:
  build-and-test:
    jobs:
      - build-and-test
  lint:
    jobs:
      - lint
